#spring:
#  application:
#    name: discovery-server
#  cloud:
#    config:
#      name: discovery-server
#      uri: http://localhost:8080/config
#  config:
#    import: optional:configserver:http://localhost:8080/config


server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false


#spring:
#  zipkin:
#    baseUrl:
#
#
#  sleuth:
#    sampler:
#      probability: 1